<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Customer;
use App\Models\User;
use App\Models\SaleItem;
use App\Models\Product;
use App\Models\Payment;
use App\Models\PaymentMethod;
use App\Models\Transaction;
use App\Models\Report;
use App\Models\TaxRate;
use App\Models\Promotion;
use App\Models\Category;
use App\Models\Inventory;

class Sale extends Model
{
    use HasFactory;

    protected $fillable = [
        'customer_id',
        'user_id',
        'total_amount',
        'sale_date',
    ];

    protected $casts = [
        'sale_date' => 'datetime',
    ];    
    
    /**
     * Get the customer associated with the sale.
     */
    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    /**
     * Get the user (cashier or staff) who made the sale.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the items in this sale.
     */
    public function saleItems()
    {
        return $this->hasMany(SaleItem::class);
    }

    /**
     * Get the payments for the sale.
     */
    public function payments()
    {
        return $this->hasMany(Payment::class);
    }

    /**
     * Get the transactions generated by this sale.
     */
    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    /**
     * Get the reports related to this sale, if any.
     */
    public function reports()
    {
        return $this->hasMany(Report::class);
    }

    /**
     * Get the products sold in this sale (indirectly via SaleItems).
     */
    public function products()
    {
        return $this->hasManyThrough(Product::class, SaleItem::class);
    }

    /**
     * Get the payment methods used in this sale (via payments).
     */
    public function paymentMethods()
    {
        return $this->hasManyThrough(PaymentMethod::class, Payment::class);
    }

    /**
     * Get the tax rates applied to this sale (via sale items or products).
     */
    public function taxRates()
    {
        return $this->hasManyThrough(TaxRate::class, Product::class);
    }

    /**
     * Get the promotions applied to this sale (via products or directly).
     */
    public function promotions()
    {
        return $this->hasManyThrough(Promotion::class, Product::class);
    }

    /**
     * Get the inventories affected by this sale (via products).
     */
    public function inventories()
    {
        return $this->hasManyThrough(Inventory::class, Product::class);
    }

    /**
     * Get the product categories involved in this sale.
     */
    public function categories()
    {
        return $this->hasManyThrough(Category::class, Product::class);
    }
}
